{
 "title": "Edgeworld",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Response by status code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "number_of_2xx", "legendFormat": "2xx" },
    { "expr": "number_of_3xx", "legendFormat": "3xx" },
    { "expr": "number_of_4xx", "legendFormat": "4xx" },
    { "expr": "number_of_5xx", "legendFormat": "5xx" }
   ]
  },
  {
   "title": "Offload percentage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "offload_rate", "legendFormat": "offload(%)" }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "edge_response_time", "legendFormat": "Edge (ms)" },
    { "expr": "origin_response_time", "legendFormat": "Origin (ms)" }
   ]
  },
  {
   "title": "Req/s by cacheability",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "num_cache_hit", "legendFormat": "CACHE_HIT" },
    { "expr": "num_cache_miss", "legendFormat": "CACHE_MISS" }
   ]
  },
  {
   "title": "Req/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "requests_per_second", "legendFormat": "# req/s" }
   ]
  },
  {
   "title": "Bytes/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bytes_per_second", "legendFormat": "bytes/s" }
   ]
  }
 ]
}